language: generic
dist: bionic

install:
  - sudo apt-get install python3-pip python3-setuptools
  - pip3 install -r requirements.txt

script:
  - make clean
  - make

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
