language: generic
dist: bionic

install:
  - sudo snap install jsonnet

script:
  - make clean
  - make

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
